import { type NextPage } from "next";
import Head from "next/head";
import Header from "~/components/Header";
import LatestVideo from "~/components/LatestVideo";
import Sponsors from "~/components/Sponsors";
import TheCrew from "~/components/TheCrew";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto min-h-[100svh] max-w-4xl">
        <Header />
        <LatestVideo />
        <TheCrew />
        <Sponsors />
      </div>
    </>
  );
};

export default Home;
