import { type NextPage } from "next";
import Head from "next/head";
import Header from "~/components/Header";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-[100svh] bg-[#D9D9D9]">
        <Header />
      </div>
    </>
  );
};

export default Home;
